manifest_version: 1

settings:
  enable_custom_role_profiles: false # TODO: re-enable after teardown
  allow_space_admin_in_custom_profiles: false # TODO: re-enable after teardown

role_profile_actions:
  stack-manager:
    - SPACE_READ
    - SPACE_WRITE
    - RUN_TRIGGER
    - TASK_CREATE
    - STACK_CREATE
    - STACK_UPDATE
    - STACK_DELETE
    - STACK_LOCK
    - STACK_UNLOCK
    - STACK_ADD_CONFIG
    - STACK_DELETE_CONFIG
    - STACK_SET_CURRENT_COMMIT
    - STACK_SYNC_COMMIT
    - STACK_UPLOAD_LOCAL_WORKSPACE
    - STACK_STATE_READ
  space-manager:
    - SPACE_READ
    - SPACE_WRITE
    # - SPACE_ADMIN # TODO: re-enable after teardown
  policy-manager:
    - SPACE_READ
    - SPACE_WRITE
  readonly-auditor:
    - SPACE_READ

role_profile_role_slugs:
  stack-manager: sl-mgmt-role-stack-manager
  space-manager: sl-mgmt-role-space-manager
  policy-manager: sl-mgmt-role-policy-manager
  readonly-auditor: sl-mgmt-role-readonly-auditor
  space-admin: space-admin
